### ISSUE TITLE
Mac laptops are unable to ssh into remote servers over wireless.

### ISSUE THREAD

**Issue by tatwell** [chapmanu/ansible-workstation#2]
Student devs have to be cabled in to ethernet to ssh into staging servers. This is a problem because it require disrupting other developers to borrow their ethernet connection.

**Comment by khafa100** [comment]
After getting help from IS&T a solution has been found.

1) Connect to the eduroam wifi and log in using your chapman email and password.
2) Connect to the Chapman VPN.
    - Click on the VPN icon and select 'Open Network Preferences...'
    - Click on 'Advanced...'
    - Confirm that the checkbox for 'Send all traffic over VPN connection' is marked.
    - Click 'OK' > 'Apply' > 'Save Configuration'

You should be able to access staging sites and the wiki page over wifi now. These steps are also found on the [wiki page](https://wimops.chapman.edu/wiki/Chapman_VPN).

*Note: If you receive a `Permission denied (publickey)` error while trying to deploy then type:

`ssh-add`

You may need to do this now and then whenever you deploy. A reason for why this must be done more than once hasn't been found yet, but it works for now.
